### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by WinniyGD** [Tinglok/avstyle#1]
Hi, When I run the codes, the Interpreter throws the following error.

ModuleNotFoundError: No module named 'models.stylegan_networks'

[ from .stylegan_networks import StyleGAN2Discriminator, StyleGAN2Generator, TileStyleGAN2Discriminator ] - networks.py

**Comment by Tinglok** [comment]
Hi sorry for the delay,
I just uploaded the related file. Hope it helps!

**Comment by WinniyGD** [comment]
Thx . It's useful!
