### ISSUE TITLE
split.py error problem 

### ISSUE THREAD

**Issue by yangma12** [Tinglok/avstyle#4]
Hi, sorry to bother you.
Youtube-dl seems to have a problem recently, and the video cannot be downloaded. According to the official repair method, I used yb-dlp to download the video, but split.py cannot run. I don’t know if it is the naming problem of the data or what is the reason. The following code video_list The value is an array with only one element './youtube'
```
video_path = './youtube'
video_list = sorted(glob(video_path))
```
What is the storage location and naming convention of the data set?
Thx.

**Comment by Tinglok** [comment]
Hi, you should specify the video path like this: `video_path = '/path/to/youtube/*.mp4'`.

**Comment by yangma12** [comment]
thank you for your reply
